
development:
  adapter: postgresql
  encoding: unicode
  database: my_project
  pool: 5
  timeout: 5000
  username: rails
  password: rails

test:
  adapter: postgresql
  encoding: unicode
  database: my_project
  pool: 5
  timeout: 5000
#  username: mike
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_project
  pool: 5
  timeout: 5000
#  username: mike
  password: